### ISSUE TITLE
Document port binding failure issue in Troubleshooting

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv2-driver#127]
From slack conversation on 6/8, in #general channel:

"OS is nLinux which is a Debian derivative and I am running HPE Helion OpenStack hos-3.0.0 (build 01-1017).

[3:26]  
I have been following the process at http://f5-openstack-lbaasv2.readthedocs.io/en/liberty/index.html.  I have completed installing the f5 specific sofware and have created a loadbalancer/listener/pool/members but it appears that the vip does not exist.

[3:27]  

```
stack@helion-cp1-c0-m1-mgmt:~$ neutron port-show 0bab1ab1-2320-4640-ace2-9beff807c945
+-----------------------+-----------------------------------------------------------------------------------------------------+
| Field                 | Value                                                                                               |
+-----------------------+-----------------------------------------------------------------------------------------------------+
| admin_state_up        | True                                                                                                |
| allowed_address_pairs |                                                                                                     |
| binding:host_id       | helion-cp1-c1-m2-mgmt:9a2f636b-f1f7-5c10-9e46-ef562c68eff3                                          |
| binding:profile       | {}                                                                                                  |
| binding:vif_details   | {}                                                                                                  |
| binding:vif_type      | binding_failed                                                                                      |
| binding:vnic_type     | normal                                                                                              |
| device_id             | 391455e6-2e09-53da-8c2d-9f2a462cfb4c                                                                |
| device_owner          | network:f5lbaasv2                                                                                   |
| dns_assignment        | {"hostname": "host-10-1-0-24", "ip_address": "10.1.0.24", "fqdn": "host-10-1-0-24.openstacklocal."} |
| dns_name              |                                                                                                     |
| extra_dhcp_opts       |                                                                                                     |
| fixed_ips             | {"subnet_id": "5aaff260-5658-45af-84df-830ef1236538", "ip_address": "10.1.0.24"}                    |
| id                    | 0bab1ab1-2320-4640-ace2-9beff807c945                                                                |
| mac_address           | fa:16:3e:7b:ce:07                                                                                   |
| name                  | loadbalancer-2313f806-069d-4834-99c6-87f9c31b0038                                                   |
| network_id            | 8accef85-bb8d-4417-ac7f-26ce6e5c95a4                                                                |
| security_groups       | eae22459-abca-40b3-8956-b4dc37173f4a                                                                |
| status                | DOWN                                                                                                |
| tenant_id             | 1129de61e6704487b6e76675c4d076ad                                                                    |
+-----------------------+-----------------------------------------------------------------------------------------------------+
```
#### Agent Version

unknown
#### Operating System

Debian 
#### Environment

physical F5 big-ip appliance (3600)
#### OpenStack Release

Liberty
#### Description

"

```
neutron/neutron-server.log:2016-06-08 22:04:14.651 7030 DEBUG routes.middleware [req-774e4ee6-6b81-406f-861c-6eaa8e84a1e1 ad8dd2209a614c2b8108a59fdf2c580b 1129de61e6704487b6e76675c4d076ad - - -] No route matched for GET /ports/3088ec79-81d2-420d-b8af-a6b9c12c7ccd.json __call__ /opt/stack/venv/neutron-20160503T082438Z/lib/python2.7/site-packages/routes/middleware.py:106
```

[4:33]  
If I go into the admin interface for the f5 box and look at network/arp/dynamic list I can see the IP addresses of my servers in the pool but I only see 'incomplete' for the mac addresses.
"

**Comment by jputrino** [comment]
also need to document the following:
If your BIG-IP is a VE instance running in your cloud, you may need to enable allowed address pairs. To do, edit `/etc/neutron/services/f5/f5-openstack-agent.ini` and uncomment the line 414: `l3_binding_driver = f5_openstack_agent.lbaasv2.drivers.bigip.l3_binding.AllowedAddressPairs`.

**Comment by nickjhpe** [comment]
Attaching files as requested.
[neutron-server.zip](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/307513/neutron-server.zip)
[f5-openstack-agent.zip](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/307514/f5-openstack-agent.zip)

[conf_files.zip](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/307516/conf_files.zip)

**Comment by jputrino** [comment]
from @jgruber, for documentation: 
"There are ports created for the express purpose of allocating fixed_ip addresses from tenant subnets.  In the process of orchestrating the L3 networking configuration of the BIG-IP on a tenant network, we need to allocate L3 (IP) addresses for the BIG-IP to use on the tenant subnet. The way we decided to do that was to create ‘dummy ports’ in order to associated fixed-ips (L3 addresses) to them. Dummy ports don’t have a managed ‘VIF binding’ as they don’t represent Nova managed VIFs. Thus the VIF binding will always show ‘failed’."
