### ISSUE TITLE
Update trademarks in docs to match F5 branding style guide

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv2-driver#138]
Per updated style guide (June 2016): "Apply trademarks to first mentions of products and technologies in body copy (rather than headlines, subheads, captions, etc.)." 

Ongoing -- update docs as they're edited.

**Comment by dflanigan** [comment]
@jputrino Is work completed for issue #138 ?  What is the DoD for this issue ?

**Comment by jputrino** [comment]
@dflanigan - you can mark it as complete if you want to; this is an ongoing thing.
