### ISSUE TITLE
Unable to create detached pool

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-lbaasv2-driver#155]
#### Agent Version

master (this is a bug for Mitaka release)
#### Operating System

CentOS 7
#### OpenStack Release

Mitaka
#### Description

New feature in Mitaka release allows the operator to create a pool and not bind it to a listener.  The F5 agent throws an error when attempting this operation.
#### Deployment

Single OpenStack controller with one F5 agent managing 1 BIG-IP VE

**Comment by dflanigan** [comment]
Need for Mitaka L7 routing feature.
