### ISSUE TITLE
Break L2/L3 segmentation modes features out into separate docs

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv2-driver#160]
#### Agent Version

Liberty +
#### Description

Each of the features under L2/L3 Segmentation Modes should probably have its own feature doc. Could possibly just break it into L2 and L3.

**Comment by dflanigan** [comment]
@jputrino is this issue still valid (#160)

**Comment by jputrino** [comment]
@dflanigan - yes, this needs to be done. However, you can close this issue if you want to, I can make it part of #243.
