### ISSUE TITLE
The "add_f5agent_environment" needs more documentation

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#232]
Presumably _most_ of the content is included in the docstrings in the code, but that needs to be extracted, formatted, and committed in the appropriate way.    This is among the first times we've done this with this project, so the protocol may need refinement.

Code incorporation is managed here:  #231 .

**Comment by jputrino** [comment]
1. Document the configuration utility via sphinx autodoc.
2. Document differentiated services using the feature template.
