### ISSUE TITLE
Fixes needed for refactored driver_v2 module

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#289]
* Details: I broke the api for the driver_v2 interface into the agent_rpc module when I refactored driver_v2. I need to fix those issues, while still maintaining the old api interface.

#### OpenStack Release
This is only applicable to the feature.l7switching branch

**Comment by dflanigan** [comment]
Work completed by Paul on Nov 18.
