### ISSUE TITLE
Implement lbaas-loadbalancer-stats command

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-lbaasv2-driver#29]
Add support for returning load balancer stats:
active_connections 
bytes_in 
bytes_out
total_connections

**Comment by dflanigan** [comment]
@jlongstaf lets meet to figure out how to get this collapsed. Is this be part of L7 content switching feature ?

**Comment by jlongstaf** [comment]
No, this is not part of L7 content switching. I'm working on pull requests to collapse into liberty.
