### ISSUE TITLE
image_ref field needs to be dynamically added to tempest.conf file

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#296]
* Title: image_ref field needs to be dynamically added to tempest.conf file

* Details: To run neutron-lbaas tempest scenario tests, we need to pass the image reference id of Cirros image to tempest.conf file. This id changes between each stack setup, so it has to be passed to tempest.conf after stack creation.

#### OpenStack Release
Liberty

**Comment by dflanigan** [comment]
Is this a TLC update ?

**Comment by szakeri** [comment]
This is a change in the liberty branch of driver that will update systest tempest_v2driver_install.sh script. Then the output will be used in Prodactivity.

**Comment by szakeri** [comment]
There is a fix for this bug in pull request #297.
