### ISSUE TITLE
Newton support for F5 LBaaSv2

### ISSUE THREAD

**Issue by d032956** [F5Networks/f5-openstack-lbaasv2-driver#315]
We use SUSE cloud 6 with openstack liberty . Currently we plan the upgrade processes to SUSE cloud 7 . 
SUSE cloud 7 use openstack Newton.  The latest lbaasv2 agent from F5 v9.1 is for openstack mitaka . 
Is there a roadmap for lbaasv2 Newton ? 

#### Agent Version
v 8.1 

#### Operating System
SUSE SC6   / SC7 

#### OpenStack Release
Liberty / Newton 

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: 3

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
<Describe the bug in detail, steps taken prior to encountering the issue, yand a short explanation of you have deployed openstack and F5 agent>

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by mattgreene** [comment]
Qualifying "F5 on Newton" is scheduled for next quarter (Jan-Mar).  This will happen for the generic community OpenStack, not specifically for SuSE Cloud, so there may be some additional integration pieces that delay support for "F5 on Newton on SuSE Cloud".

**Comment by jat190** [comment]
I would like to add another request for this. I have two projects that I am working on that will be using Newton and we'd like to start this work in the middle to end of January.

**Comment by panxia6679** [comment]
@mattgreene, any news about "F5 on Newton"? will it be delivered as planned? Thanks.

**Comment by mattgreene** [comment]
@panxia6679:  We're actively working on it now.  It will show up in a beta release direct to github within weeks.
