### ISSUE TITLE
Teardown of tenant folder fails when loadbalancer deleted 

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#329]
* Title: Teardown of tenant folder fails when loadbalancer deleted 

* Details:
When creating and destroying a loadbalancer on Mitaka release, the virtual address is removed
but the tenant folder and route domain remain.

#### Agent Version
Head mitaka branch

#### Operating System
Ubuntu/RedHat

#### OpenStack Release
Mitaka

#### Bug Severity 
3

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
Create a loadbalancer at neutron api
Delete the loadbalancer.

VIP is gone but the tenant folder remains.  This suggests that the tenant folder cleanup is not being called or failing.

#### Deployment
Mitaka/undercloud.

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by dflanigan** [comment]
Issue resolved with merge #330
