### ISSUE TITLE
Tempest tests need to add vine to requirements

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#341]
Failed to run a basic tempest test run b/c the requirements.test.txt is missing vine

After I installed vine everything worked fine.

#### Agent Version
9.0.1

#### Operating System
CentOS 7

#### OpenStack Release
Mitaka

#### Bug Severity 
Impacts tests.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
<Describe the bug in detail, steps taken prior to encountering the issue, yand a short explanation of you have deployed openstack and F5 agent>

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by dflanigan** [comment]
revisit this bug after new testing code from Shawn is merged:

https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/355

**Comment by dflanigan** [comment]
Rich now thinks that this is a problem any more.
