### ISSUE TITLE
Requirements file imports neutron stable/mitaka before pinned version of neutron-lbaas

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#343]
The requirements.test.txt file indicates what dependencies are required for the testing.  However,
There is an error in the order in which we cite these dependencies.

The dependency that is specified as: 

git+https://github.com/openstack/neutron.git@stable/mitaka

Imports many newer versions of the neutron packages than are included by:

git+https://github.com/openstack/neutron-lbaas.git@8.3.0

This creates problems when running the tests that rely on messaging to verify result.  There are API incompatibilities between kombu 3.0.32 and the version (4.0.X) that neutron stable/mitaka installs.

**Comment by dflanigan** [comment]
No longer an issue since Makefile refactor
