### ISSUE TITLE
Shared pools tempest test fails with lb not reaching 'ACTIVE' status

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#416]
#### Agent Version
9.2.0

#### OpenStack Release
Mitaka

#### Description
When running the test `api/test_pools.py::PoolTestJSON::test_create_shared_pools`, it fails with loadbalancer failed to reach ACTIVE status. I will update this bug to have the f5-openstack-agent log or server log entry as well.

```
Traceback (most recent call last):
  File "/home/testlab/f5-openstack-lbaasv2-driver/f5lbaasdriver/test/tempest/tests/api/test_pools.py", line 80, in test_create_shared_pools
    first_listener = self._create_listener(**first_listener_kwargs)
  File "/home/testlab/f5-openstack-lbaasv2-driver/f5lbaasdriver/test/tempest/tests/api/base.py", line 264, in _create_listener
    cls._wait_for_load_balancer_status(cls.load_balancer.get('id'))
  File "/home/testlab/f5-openstack-lbaasv2-driver/f5lbaasdriver/test/tempest/tests/api/base.py", line 257, in _wait_for_load_balancer_status
    operating_status=operating_status))
tempest.lib.exceptions.TimeoutException: Request timed out
Details: Wait for load balancer ran for 60 seconds and did not observe 9454091b-f254-40c9-b18f-fbdfcdb0a361 reach ACTIVE provisioning status and ONLINE operating status.
```
#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by pjbreaux** [comment]
This does appear to be a test issue since running the test by itself does not reproduce the failure.

**Comment by dflanigan** [comment]
@pjbreaux Is this bug fixed ?

**Comment by pjbreaux** [comment]
@dflanigan  It's not.
