### ISSUE TITLE
ReadTheDocs README.rst fixups

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#44]
@jputrino 
There's still a directive to 'pip install f5-sdk'

```
Install the F5® SDK
```
```bash
$ pip install f5-sdk
```

It should be removed.

Also we should remove the initial:  "$ " from all copy-n-pasteable commands, so they will work automatically.

**Comment by jputrino** [comment]
@zancas - using the `$` and `#` in the instructions is a prompt to the user what role they should be logged in as and is used across our OpenStack documentation. I think it's more useful in that regard, as it's easy to just not copy the prompt. Has installing the plugin components without installing the f5-sdk first been vetted (I haven't had a chance this week)? If so, I will remove it.

**Comment by zancas** [comment]
Yes, I've gone through the readme three times without running:



'pip install f5-sdk'



________________________________

**Comment by jputrino** [comment]
Also: the readme needs to be corrected/updated when the documentation is migrated from f5-openstack-lbaasv2 to this repo and f5-openstack-agent.
