### ISSUE TITLE
service_builder does not use the segment physical network name for network definition

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#452]
Service builder is not completely populating the network dictionary with all the values from the segments table.  The error is that the phyiscal_network_name is assumed to be defined in the top-level segment, but this is not always the case.

**Comment by dflanigan** [comment]
@richbrowne : could you add some details, using the issue template, so that we can set Priority & Severity.  Thanks.
