### ISSUE TITLE
Creating a Loadbalancer for another tenant failing community BVT test

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-lbaasv2-driver#459]
#### Agent Version
9.2.0

#### Operating System
RHEL 7.3

#### OpenStack Release
Mitaka

#### Bug Severity 
Severity: 5

#### Description
according to community BVT test

```
neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_for_another_tenant
```

The loadbalancer should be created with provisioning_status='ACTIVE' and operational_status='ONLINE' with the loadbalance tenant_id set to the explicit tenant_id supplied to the create loadbalancer call.. regardless if the subnet_id for the loadbalancer is not in the same tenant.

#### Deployment
Run

```
neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_for_another_tenant
```

Note: I'm not sure this should work unless the loadbalacner was created by admin.

**Comment by richbrowne** [comment]
Note:  this works for the admin user if the tenant-id is specified with the --tenant-id option, or the OS_TENANT_NAME env variable is set to the project id of the subnet.

**Comment by szakeri** [comment]
We don't support shared network, if a test tries to run shared network scenario, it will created a loadbalancer that will be in the error state.
We want to make sure that if we encounter this failure, we can manually delete the loadbalancer.
To create this issue, I performed the following steps:
1- I modified the test "neutron_lbaas.tests.tempest.v2.api.test_load_balancers_admin.LoadBalancersTestJSON.test_create_load_balancer_for_another_tenant" 
and removed the addCleaup method.
2- AddCleanup method calls _delete_load_balancer method with the loadbalancers' ids and deletes the loadbalancers using tempest RestClient calls.
3- AddCleanup makes sure to delete all the resources created during test execution so as a result, it will clean the loabalancer in the error state too.
4- As a result of removing addCleaup method, the loadbalancer will stay in the error state and will not get deleted.
5- Then I manually removed the loadbalancer by running "neutron lbaas-loadbalancer-delete $LB-ID" and confirmed that the loadbalancer got deleted properly.
6- As a result of deleting the loadbalancer, neutron cleaned up the ports associated with it too.

**Comment by szakeri** [comment]
@dflanigan @mattgreene Can we close this?

**Comment by zancas** [comment]
@mattgreene, @szakeri believes we don't support this (see above), unless I hear otherwise I will exclude this test from our automated test runs.

**Comment by mattgreene** [comment]
This is a known limitation with the F5 product and will be addressed in a future release.  Exclude from automated regression.

**Comment by dflanigan** [comment]
Known limitation. Excluded from automated regression.
