### ISSUE TITLE
Driver sets VIP port owner

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#461]
#### Description
The driver "takes ownership" of the VIP port (which is created by the load balancer creation operation), and this is unnecessary. This appears to directly affect the way the port is handled in neutron, especially upon deletion. We are making this change in the mitaka branch to troubleshoot nightly failures.

#### OpenStack Release
applies to mitaka currently

**Comment by dflanigan** [comment]
@pjbreaux and @mattgreene can I close this ?

**Comment by jgruber** [comment]
Please assure that the fix removes the port errors for the loadblancer port the neutron server log.
