### ISSUE TITLE
Setting session_persistence to None does not clear session persistence on a pool cases a scenario test to fail

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-lbaasv2-driver#463]
#### Agent Version
9.0.2.1

#### Operating System
RHEL 7.3

#### OpenStack Release
Mitaka

#### Bug Severity 
Severity: 5

#### Description
Community tempest test 

neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.TestSessionPersistence.test_session_persistence

fails with errors 

Wait for pool ran for 10 seconds and did not observe c871b9c1-b382-4956-ba3c-b7afd26d27a1 update session persistence type to None

You can increase the timeout in the test to whatever you want, the API sets session_persistence to None and the pool session_persistence never clears from the last set value (APP_COOKIE). 

#### Deployment

```
testr run neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.TestSessionPersistence.test_session_persistence
```

**Comment by jgruber** [comment]
It was decided in the private cloud meeting today that this is a blocking issue to deploying with Red Hat as it is failing a legit community scenario test:

neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.TestSessionPersistence.test_session_persistence

**Comment by mattgreene** [comment]
@jgruber : PD controls the priority field, not the submitter.  P1 means we drop everything to work on this issue, which we are not doing.

**Comment by jgruber** [comment]
upgraded to P1 as this is now a blocker for Private Cloud bundle release with OSPv9

**Comment by mattgreene** [comment]
Resolved via https://github.com/F5Networks/f5-openstack-agent/pull/640

**Comment by jgruber** [comment]
9.3.1 release failing 

`neutron_lbaas.tests.tempest.v2.scenario.test_session_persistence.TestSessionPersistence.test_session_persistence`

Error is:

`Wait for pool ran for 10 seconds and did not observe 142ab218-a9cf-48e5-91e6-5db1ed4a6e6c update session persistence type to None`

Failed with a clean Mitaka environment with only single test run.

**Comment by mattgreene** [comment]
@jgruber My understanding is that we found and fixed a bug, but it's different than this new comment from Jun 12.  Please open a new bug so we can find/fix the new issue without confusing the original issue.
