### ISSUE TITLE
Enable a supported "non pip" install of F5 components on RHEL OSPv9

### ISSUE THREAD

**Issue by pdp2shirts** [F5Networks/f5-openstack-lbaasv2-driver#475]
#### Agent Version
9.2.0

#### Operating System
RHEL OSPv9

#### OpenStack Release
RHEL OSPv9

#### Bug Severity 

Severity: <2>

Entered as a 2 because this is preventing the "Private Cloud OpenStack Bundle" form being certified and jointly validated by F5 and Red Hat. The certification is one of the cornerstones of the bundle offerings. This bundle is scheduled to go live 3/31/2017.

#### Description
While there are rpm packages for the following:

https://github.com/F5Networks/f5-icontrol-rest-python/releases/download/v1.1.0/f5-icontrol-rest-1.1.0-1.el7.noarch.rpm
https://github.com/F5Networks/f5-common-python/releases/download/v2.1.0/f5-sdk-2.1.0-1.el7.noarch.rpm 
https://github.com/F5Networks/f5-openstack-agent/releases/download/v9.2.0/f5-openstack-agent-9.2.0-1.el7.noarch.rpm 
https://github.com/F5Networks/f5-openstack-lbaasv2-driver/releases/download/v9.2.0/f5-openstack-lbaasv2-driver-9.2.0-1.el7.noarch.rpm 

and the install of these packages on Red Hat OSPv9 is supported. The RPM install of the f5-sdk fails on RHEL OSPv9 without first performing a 

pip install ordereddict 

To install pip you have to either curl it to the box, or enable the EPEL repos, both of which break the supportability from a red Hat perspective.

Ordereddict is also an unsupported python package from Red Hat's point of view.

#### Deployment

Single RHEL OpenStack v9 controller with one F5 agent managing a cluster of 2 BIG-IP iSeries 5800s. This is a standard RHEL OSPv9 Director Undercloud, which deploys the OSPv9 Overcloud of 1 controller and two Compute.>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
Next release of the SDK. This may be a python-idk issue but I'm entering it here because it prevents our agent and drivers from being fully-certified by Red Hat. John Gruber talked to Rich Browne about this I believe but I can not find an issue entered for tracking it.

#### Description
<Describe the enhancement request in detail>

**Comment by mattgreene** [comment]
This issue is fixed in f5-sdk version 2.2.2.  The next openstack driver/agent release (9.3.0) will include the fix.

**Comment by mattgreene** [comment]
9.3.0 (pre-release) is now available on github.
