### ISSUE TITLE
LBaaSv2 solutions test has broken graphics links

### ISSUE THREAD

**Issue by jgruber** [F5Networks/f5-openstack-lbaasv2-driver#480]
#### Agent Version
NA

#### Operating System
NA

#### OpenStack Release
Latest

#### Bug Severity 
2

#### Description
http://f5-openstack-lbaasv2-driver.readthedocs.io/en/latest/solution-test-plan.html

shows broken image links for the Network Architecture graphics. Specifically links to:

http://f5-openstack-lbaasv2-driver.readthedocs.io/en/media/f5-lbaas-test-architecture-grm.png
http://f5-openstack-lbaasv2-driver.readthedocs.io/en/media/f5-lbaas-test-architecture-l2adj.png

Hopefully this is just a 'getting there' thing.

Thanks!

**Comment by dflanigan** [comment]
@jgruber Why did you add the Blocked label ?

**Comment by dflanigan** [comment]
Fixes tag not used correctly to close automatically.
