### ISSUE TITLE
[Bug] [Docs] Documentation has duplicate link for Global Routed Mode (in Supported Features)

### ISSUE THREAD

**Issue by litmaj0r** [F5Networks/f5-openstack-lbaasv2-driver#482]
#### Agent Version
9.3.0b2

#### Operating System
Not Applicable 

#### OpenStack Release
Found at 9.3.0b2 (Mar 24, 2017) but goes back to initial commit 

#### Bug Severity 
Severity: 5

#### Description
A duplicate link to the Global Routed Mode documentation exists, even though the destination is the same. Removing the redundancy should help clean up the docs and avoid potential customer confusion. 

PR w/ fix to come. 

#### Deployment
Not Applicable

**Comment by mattgreene** [comment]
Fix has been merged to master.
