### ISSUE TITLE
Test create esd tempest test requires pre-existing demo policy on the BIG-IP

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#496]
* Title: Test setup for [api/test_esd.py::ESDTestJSON::test_create_esd](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/mitaka/f5lbaasdriver/test/tempest/tests/api/test_esd.py#L78) needs a pre-existing policy on the BIG-IP called 'demo-policy'

#### Agent Version
mitaka agent with ESD feature merged in

#### OpenStack Release
mitaka

#### Bug Severity 
This is a test bug

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
The setup for this particular test requires a preceding step of creating a policy called 'demo-policy' for the test to run properly. Otherwise the agent fails to find this policy and the test fails.
Associated Tests:
["test_esd::ESDTestJSON.test_create_esd"]

**Comment by ssorenso** [comment]
Need to isolate to see if this is the same error:
```
Traceback (most recent call last):
  File "/home-local/jenkins/workspace/openstack/driver/mitaka/12.1.2-undercloud-vxlan/f5lbaasdriver/test/tempest/tests/api/test_esd.py", line 90, in test_create_esd
    raise ex
_pytest.assertion.reinterpret.AssertionError: assert <bound method BigIpClient.virtual_server_has_value of <f5lbaasdriver.test.tempest.services.clients.bigip_client.BigIpClient object at 0x7ff42aafbb50>>('Project_f6231e57-2ae7-4cdc-aa46-4225f87fc368', 'fallbackPersistence', '/Common/source_addr', 'Project_de4d1806a4e445b398baf2b8243de756')
 +  where <bound method BigIpClient.virtual_server_has_value of <f5lbaasdriver.test.tempest.services.clients.bigip_client.BigIpClient object at 0x7ff42aafbb50>> = <f5lbaasdriver.test.tempest.services.clients.bigip_client.BigIpClient object at 0x7ff42aafbb50>.virtual_server_has_value
 +  and   'Project_de4d1806a4e445b398baf2b8243de756' = <f5lbaasdriver.test.tempest.tests.api.test_esd.ESDTestJSON.test_create_esd[smoke] id=0x7ff428d9d910>.partition
```
Test Impact:
* openstack_driver_mitaka_12.1.2-undercloud-vxlan.59.consoleText
  * failures
  * ESDTestJSON.test_create_esd
  * md5sum:fe67d31dd8eae956660ec601cd018b25

**Comment by richbrowne** [comment]
This test is passing now.
