### ISSUE TITLE
Liberty nightly test runs needs to set a .pytest.rootdir

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#526]
* Title: Liberty nightly test runs needs to set a .pytest.rootdir

#### Agent Version
<Fill in the version you have installed, such as 2.0.1>

#### Operating System
<Fill in the host OS of the machine running the agent, such as CentOS 7>

#### OpenStack Release
liberty

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
The liberty test runs now have a --meta option to pytest to exclude certain sets of tests. This change caused the pytest root directory to change, which means the suite name in trtl also changed in nightly gumballs. That means that newer gumballs results don't line up with the historical results, because gumballs views those two separate suite names as different tests. We need to make them line up again. We do that by creating a file '.pytest.rootdir' in the appropriate location (/home/buildbot) so that gumballs is happy again.

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by dflanigan** [comment]
@pjbreaux When will the Pull Request to fix this make it to Master ?
