### ISSUE TITLE
The f5-lbaasv2-process-on-controller_Project queue is missing in new install

### ISSUE THREAD

**Issue by busterswt** [F5Networks/f5-openstack-lbaasv2-driver#543]
#### Agent Version
9.3.0 final

#### Operating System
Ubuntu 16.04.1

#### OpenStack Release
Newton

#### Bug Severity 
Severity: 2

#### Description
Using v9.3.0 (final) of the f5-openstack-lbaasv2-driver, we have identified an issue where the F5 lbaas agents are not checking in and cannot be seen with a 'neutron agent-list'. Further troubleshooting found that the 'f5-lbaasv2-process-on-controller_Project' queue is not being created upon startup of the neutron-server service. The agent queues are visible with rabbitmqctl, however. 

Looking at the code, we found some changes since the previous release (v9.3.0b2) that are likely responsible. In fact, downgrading to v9.3.0b2 found the queue being created as expected upon startup agents were able to check in, and the driver performed as advertised.

This deployment of the F5 lbaas driver is the first in this environment. No F5 or lbaas-related queues existed prior to this deployment of the driver and agents.

#### Deployment
This is an OpenStack-Ansible (OSA) based deployment of the Newton release of OpenStack. There are three (3) neutron-server services across three (3) infra/controller nodes that are load balanced. The F5 lbaas agents are distributed across all compute nodes in the environment.

The BIG-IP system is composed of a pair of i7800s running v12.x. The lbaas driver is configured to manage a pair of vCMP guests in HA mode on those i7800s

**Comment by busterswt** [comment]
This can also be tracked internally via 1-3011629200. Apologies for the redundancy, but there is pressure to get this resolved.

**Comment by mattgreene** [comment]
@busterswt: Newton is not yet supported.  9.3.0 is the latest version for OpenStack Mitaka.  A future 10.x version will be released that supports Newton.  Please look [here](http://f5-openstack-docs.readthedocs.io/en/latest/releases_and_versioning.html#releases-and-support) for supported versions.
