### ISSUE TITLE
Openstack LBaaSv2 v9.3: Could not delete pool member from CLI or GUI

### ISSUE THREAD

**Issue by dflanigan** [F5Networks/f5-openstack-lbaasv2-driver#560]
* Openstack LBaaSv2 v9.3: Could not delete pool member from CLI or GUI

* Details: For bugs, copy and paste the following template into your new issue and fill it out.

#### Driver Version
v9.3

Severity: <Fill in level: 1 through 5>
Severity 2

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description

Could not delete pool member from CLI or GUI

**Comment by szakeri** [comment]
As part of investigating this SR, we found out that there is Huawei driver involved in deleting pool member which gave our driver the wrong provisioning status. This is the response I got in the SR:
FSE reported that the issue disappeared this week when he remote test for the same delete action. FSE suspected Huawei update their driver or did something to make this work. I think we can close the case. Thanks again for the help.
