### ISSUE TITLE
Member port creation handling - stable/newton

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#574]
* Details: We need to decide how to handle port creation error for a specific member in stable/newton.

#### OpenStack Release
stable/newton

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by pjbreaux** [comment]
@szakeri and @dflanigan: I think this issue has been addressed completely. We likely did not reference it directly in a PR.
