### ISSUE TITLE
BIG-IP v13.0.0.0.0.1645 image in Liberty fails test_health_monitor_basic test

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#612]
* Title: BIG-IP v13.0.0.0.0.1645 image in Liberty fails test_health_monitor_basic test
* Attachments:
  * [test_health_monitor_basic.txt](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/1081531/test_health_monitor_basic.txt)
* Details: For bugs, copy and paste the following template into your new issue and fill it out.

#### Agent Version
8.3.1

#### Operating System
Linux host-136.int.lineratesystems.com 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### OpenStack Release
Liberty

#### Bug Severity 
3

Severity: 3

#### Description
This test failed.  In comparison to previous trtl results, this appears to be a new failure as compared to 6/15's results.

#### Deployment
Standard undercloud deployment in test infra comparable to nightly.

**Comment by szakeri** [comment]
@dflanigan @mattgreene This issue can be closed, This test is a scenario test and we can't run scenario tests against overcloud deployment. We just need to add them to the exclude file for BIGIP13.

**Comment by dflanigan** [comment]
@ssorenso confirm that this test is excluded.
