### ISSUE TITLE
BIGIP-13.0.0.0.0-1645 Liberty overcloud connected test_listener_basic failed

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#613]
* Title: BIGIP-13.0.0.0.0-1645 Liberty overcloud connected test_listener_basic failed
* Attachments: 
  * [test_listener_basic.txt](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/1081541/test_listener_basic.txt)
* Details: the test failed under standard nightly comparison for 6/15.  This test passed against nightly, but failed upon initial tests runs for v13.

#### Agent Version
8.3.1

#### Operating System
Standard testlab

#### OpenStack Release
Liberty

#### Bug Severity 
3

### Description
Failed during init, or so it appears.  Teardown appears to have completed appropriately.

#### Deployment
STandard test lab for overcloud Cx'ed.

**Comment by szakeri** [comment]
@dflanigan @mattgreene This issue can be closed, This test is a scenario test and we can't run scenario tests against overcloud deployment. We just need to add them to the exclude file for BIGIP13.

**Comment by dflanigan** [comment]
@ssorenso confirm that test is excluded.
