### ISSUE TITLE
BIGIP-13.0.0.0.0.1645 Liberty Overcloud Cx'ed test_load_balancer_tls

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#615]
* Title: BIGIP-13.0.0.0.0.1645 Liberty Overcloud Cx'ed test_load_balancer_tls
* Attachments:
  * [test_load_balancer_tls.txt](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/1081568/test_load_balancer_tls.txt)
* Details: failure occurred in initial testing for BIGIP v13

#### Agent Version
8.3.1

#### Operating System
CentOS (standard lab)

#### OpenStack Release
Liberty

#### Bug Severity 
3

#### Description
Failure occurred as compared to nightly's testing of late that differs with 13.

#### Deployment
Standard overcloud connected.

**Comment by szakeri** [comment]
@dflanigan @mattgreene This issue can be closed, This test is a scenario test and we can't run scenario tests against overcloud deployment. We just need to add them to the exclude file for BIGIP13.

**Comment by dflanigan** [comment]
@ssorenso Did you confirm with Sanaz that the exclude file is correct?
