### ISSUE TITLE
BIGIP-13.0.0.0.0.1645 Liberty Overcloud Cx'ed test_create_health_monitor_empty_max_admin_state_up

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#616]
* Title: BIGIP-13.0.0.0.0.1645 Liberty Overcloud Cx'ed test_create_health_monitor_empty_max_admin_state_up
* Attachments:
  * None
* Details: failure occurred in initial testing for BIGIP v13

#### Agent Version
8.3.1

#### Operating System
CentOS (standard lab)

#### OpenStack Release
Liberty

#### Bug Severity 
3

#### Description
```
__ ERROR at setup of TestHealthMonitors.test_create_health_monitor_empty_max_admin_state_up __
test_health_monitors_non_admin.py:48: in resource_setup
    protocol='HTTP', protocol_port=80)
base.py:215: in _create_listener
    cls._wait_for_load_balancer_status(cls.load_balancer.get('id'))
base.py:208: in _wait_for_load_balancer_status
    operating_status=operating_status))
E   TimeoutException: Request timed out
E   Details: Wait for load balancer ran for 60 seconds and did not observe 7b493ae5-698a-47df-ab29-e994514b4185 reach ACTIVE provisioning stFAILED
```

#### Deployment
Standard overcloud connected.

**Comment by dflanigan** [comment]
@ssorenso please recreate the failure and attached server logs to this issue. Thanks.

**Comment by ssorenso** [comment]
@mattgreene @dflanigan, this was a bug created regarding the results in tests that should only be carried out in undercloud.  I've since created an exclude yaml for 13's overcloud deployment to keep these from running.
