### ISSUE TITLE
BIGIP-13 image 0.0.0.0.1647 does not appear to license easily

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#636]
* Title: BIGIP-13 image 0.0.0.0.1647 does not appear to license easily
* Attachments: None, this is based upon observations in the lab
* Details: the BIGIP-13.0.0.0.2.0.1671 image hotfix appears to work much more often for the SOAPLicenseClient

#### Agent Version
Any

#### Operating System
Not relevant

#### OpenStack Release
Any

#### Bug Severity 
3

#### Description
The BIGIP image for 13.0.0.0.0 does not appear to work well for the SOAPLicenseClient from within the lab with getting the box quickly licensed.  This appears to be resolved on BIG-IP for version 13.0.0.0.2.0 hot-fix.

#### Deployment
Not relevant

#### OpenStack Release
Any

**Comment by mattgreene** [comment]
Confirming this issue is resolved with BIG-IP 13.0.0.0.2.0.
