### ISSUE TITLE
Multi-provider didn't work, only one agent registered in neutron.

### ISSUE THREAD

**Issue by Sinan828** [F5Networks/f5-openstack-lbaasv2-driver#642]
#### Agent Version
9.3.1

#### Operating System
centos 7

#### OpenStack Release
Mitaka

#### Bug Severity 
Only one agent can registered in neutron when running multi-provider.

Severity: <Fill in level: 1>

#### Description
Only one agent can registered in neutron when running multi-provider.

#### Deployment
2 ltm, 2 agents, agent a manger ltm-a, agent b manger ltm-b.
1. add new provider DMZ use add_environment.py
2. restart neutron-server service
3. changed second agent environment_prefix to DMZ.
4. start second agent.

here're my config files and logs:
[new_config_logs.zip](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/1110829/new_config_logs.zip)

here is my analysis:
[my analysis.docx](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/1110831/my.analysis.docx)

**Comment by jgruber** [comment]
The patch removed the F5DriverV2 classes _handle_driver_error_ which is still referenced in the LoadBalancerManager class twice (update and stats methods). Pretty sure this needs to be put back:

```
    def _handle_driver_error(self, context, loadbalancer,
                             loadbalancer_id, status):
        pass
```

**Comment by pjbreaux** [comment]
@jgruber: I'm closing this issue, as I've opened another issue explaining this problem and a suspected fix. Take a look. https://github.com/F5Networks/f5-openstack-lbaasv2-driver/issues/739
