### ISSUE TITLE
investigating on where f5lbaasdriver/test/tempest/Docker/tempest_tests is used

### ISSUE THREAD

**Issue by szakeri** [F5Networks/f5-openstack-lbaasv2-driver#674]
* Details: 
It is not clear where "f5lbaasdriver/test/tempest/Docker/tempest_tests docker" file is used, or if it is necessary to keep it around.

#### OpenStack Release
Mitaka forward

#### Bug Severity 
For bugs enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

#### Description
<Describe the bug in detail, steps taken prior to encountering the issue, yand a short explanation of you have deployed openstack and F5 agent>

#### Deployment
<Explain in reasonable detail your OpenStack deployment, the F5 OpenStack agent, and BIG-IP(s)>
<Example: Single OpenStack controller with one F5 agent managing a cluster of 4 BIG-IP VEs>
<Example: Three OpenStack controllers in HA, each with one standalone F5 agent managing a single BIG-IP appliance>

* Details: For enhancements, copy and paste the following template into your new issue and fill it out.

#### OpenStack Release
<The earliest release in which you would like to see the enhancement>

#### Description
<Describe the enhancement request in detail>

**Comment by zancas** [comment]
It looks like this file was created by @pjbreaux on 2016-10-20.

I'm confirming that when I remove it on my test branch the Jenkins tests still run.

**Comment by zancas** [comment]
The tests pass:  

http://jenkins.pdbld.f5net.com/job/openstack/job/driver/job/newton/job/za_test_11.6.1_undercloud_vxlan/9/consoleFull

So I'm going to open a PR removing this file.

**Comment by dflanigan** [comment]
@szakeri can we close this issue ?

**Comment by szakeri** [comment]
@dflanigan This file is removed from mitaka and stable/newton, but it still exists in master. I think it will automatically be closed when we merge forward to master.
