### ISSUE TITLE
Functional Test Case failed: test_pool_CLUDS, for Overcloud BipIP v.12.0

### ISSUE THREAD

**Issue by pskergan** [F5Networks/f5-openstack-lbaasv2-driver#70]
#### Agent Version
commit hash: f84f76a

#### Driver Version
commit hash:  b7f94da

#### Operating System
CentOS 7

#### OpenStack Release
Liberty

#### Description
_______________________________________________ test_pool_CLUDS _______________________________________________

setup_with_listener = (<f5_os_test.polling_clients.NeutronClientPollingManager object at 0x10cb74190>, {u'listener': {u'default_pool_id': No...'protocol': u'HTTP', u'description':...80, u'id': u'6297e585-c011-45e0-8670-7f2f69f70529', u'name': u'test_listener'}})
bigip = <f5.bigip.BigIP object at 0x10cb74810>

    def test_pool_CLUDS(setup_with_listener, bigip):
        nclientmanager, listener = setup_with_listener
        pool_config = {'pool': {
                       'name': 'test_pool_anur23rgg',
                       'lb_algorithm': 'ROUND_ROBIN',
                       'listener_id': listener['listener']['id'],
                       'protocol': 'HTTP'}}
        # The bigip starts life with 0 pools
        # Test lbaas_list_pools
        assert not nclientmanager.list_lbaas_pools()['pools']
        assert not bigip.ltm.pools.get_collection()
        pool = nclientmanager.create_lbaas_pool(pool_config)
        pool_id = pool['pool']['id']
        assert pool['pool']['description'] == ''
        assert len(nclientmanager.list_lbaas_pools()['pools']) == 1
        # The create_lbaas_pool call adds a pool to the bigip
>       assert bigip.ltm.pools.get_collection()[0].name == 'test_pool_anur23rgg'
E       IndexError: list index out of range

test_balancer_CD.py:109: IndexError
-------------------------------------------- Captured stdout setup --------------------------------------------
'got here in the constructor'
'Entered setup/finalize.'

**Comment by szakeri** [comment]
I ran the test and 5 tests passed:

(testvenv) [testlab@host-5 functional]$ py.test --bigip=10.190.3.59 --auth_address=10.190.4.194 -v test_balancer_CD.py
<class 'f5.bigip.BigIP'>
========================================================== test session starts ==========================================================
platform linux2 -- Python 2.7.5, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/testlab/testvenv/bin/python
cachedir: ../../.cache
rootdir: /home/testlab/testvenv/f5-openstack-lbaasv2-driver, inifile:
plugins: f5-openstack-test-0.1.3, cov-2.2.1
collected 5 items

test_balancer_CD.py::test_loadbalancer_CLUDS PASSED
test_balancer_CD.py::test_listener_CLUDS PASSED
test_balancer_CD.py::test_pool_CLUDS PASSED
test_balancer_CD.py::test_member_CLUDS PASSED
test_balancer_CD.py::test_healthmonitor_CLD PASSED

======================================================= 5 passed in 34.69 seconds =======================================================

**Comment by dflanigan** [comment]
I copied off the logs and put them in my home directory on Bahamas:

/home/flanigan/neutron_logs/lbassv2-driver-issue-70/neutron_logs.tar

**Comment by pskergan** [comment]
The failed test likely resulted from missing a step in test env setup.
Closing the issue.
