### ISSUE TITLE
Add a redirect from Read the Docs to clouddocs.f5.com

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-lbaasv2-driver#717]
#### OpenStack Release
Liberty

#### Description
Now that documentation publishes to clouddocs.f5.com, we need to redirect users from read the docs to the new product documentation on clouddocs. 

This is done via javascript embedded in the html body of each page by the sphinx `rst_prolog`.

**Comment by dflanigan** [comment]
Observed commit in master. Merge message did not contain fixes tag, maybe ?

**Comment by jputrino** [comment]
@dflanigan This issue is not closed. The PR to resolve it -- #718 -- is still open.

**Comment by dflanigan** [comment]
@jputrino I fixed the description in #718. It had referenced #217 and not #717.
