### ISSUE TITLE
typo in base reference in test_common_networks.py

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#741]
https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/506e977036ef2dcdae529bae9066762d7269c900/f5lbaasdriver/test/tempest/tests/api/test_common_networks.py#L25

**Comment by zancas** [comment]
Should be "`tests.api`"

**Comment by ssorenso** [comment]
md5sum associated with this ticket:
e79ad93b93bb613a0d8c884eec081ece
