### ISSUE TITLE
teardown of test_featureoff_nosegid_listener due to neutron database conflict

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#769]
* Title: teardown of test_featureoff_nosegid_listener due to neutron database conflict
* Attachments: 
* Details:

##### Suggested Error Type
Bug... We should not ever be performing an action out of sequence that may result in us asking to perform an operation that the BIG-IP is not expecting.

##### Traceback:
```
    def remove_test_created_elements():
        posttest_registry = register_device(bigip)
        created = frozenset(posttest_registry) - pretest_snapshot
>       remove_elements(bigip, created, vlan)

conftest.py:107:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
conftest.py:78: in remove_elements
    registry[selfLink].delete()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <f5.bigip.tm.sys.db.Db object at 0x7f5272f657d0>, kwargs = {}

    def delete(self, **kwargs):
        '''Delete is not supported for db resources.

            :raises: UnsupportedOperation
            '''
        raise UnsupportedOperation(
>           "DB resources doesn't support delete, only load and refresh"
        )
E       UnsupportedOperation: DB resources doesn't support delete, only load and refresh

../../../../.tox/disconnected_service/local/lib/python2.7/site-packages/f5/bigip/tm/sys/db.py:69: UnsupportedOperation
```
##### Impacted Tests:

* `openstack_agent_mitaka_12.1.2-overcloud.6.consoleText`
  * Type: errors
  * Test: `test_featureoff_nosegid_listener`
  * md5sum:`c89ad1edb4cdbcb259017f16341f6a9f`
  * reduced(md5sum):`d41d8cd98f00b204e9800998ecf8427e`

#### Agent Version
mitaka - `f973c65be44191c8c2439c9cb46fcc94ee67b7b0`

#### Operating System
Nightly

#### OpenStack Release
Mitaka (possibly others? unconfirmed)

#### Bug Severity 
Low

#### Deployment
overcloud

**Comment by richbrowne** [comment]
This is an issue for the agent.
