### ISSUE TITLE
HA Config running into numerous ConnectionError's in Nightly

### ISSUE THREAD

**Issue by ssorenso** [F5Networks/f5-openstack-lbaasv2-driver#778]
* Title: HA Config running into numerous ConnectionError's in Nightly
* Attachments:
* Details:

##### Suggested Issue Type
Test Bug
I see this as some kind of connectivity error as most of them fail due to maximum retries reached; however, I do see a commonality of just the tail portion of the REST API call being shown for a URI in the error statements... This may be expected, though.

##### Traceback:
This is simply the first found...
```
cls = <class 'f5lbaasdriver.test.tempest.tests.api.test_esd.ESDTestJSON'>

    @classmethod
    def resource_setup(cls):
>       super(ESDTestJSON, cls).resource_setup()

cls        = <class 'f5lbaasdriver.test.tempest.tests.api.test_esd.ESDTestJSON'>

api/test_esd.py:35:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
api/base.py:43: in resource_setup
    CONF.f5_lbaasv2_driver.icontrol_password)
../services/clients/bigip_client.py:48: in __init__
    self.bigip = ManagementRoot(hostname, username, password)
/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py:124: in __init__
    self.post_configuration_setup()
/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py:91: in post_configuration_setup
    self._get_tmos_version()
/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py:96: in _get_tmos_version
    response = connect.get(base_uri)
/usr/local/lib/python2.7/dist-packages/icontrol/session.py:258: in wrapper
    response = method(self, REST_uri, **kwargs)
/usr/local/lib/python2.7/dist-packages/icontrol/session.py:427: in get
    return self.session.get(uri, **kwargs)
/usr/local/lib/python2.7/dist-packages/requests/sessions.py:480: in get
    return self.request('GET', url, **kwargs)
/usr/local/lib/python2.7/dist-packages/requests/sessions.py:468: in request
    resp = self.send(prep, **send_kwargs)
/usr/local/lib/python2.7/dist-packages/requests/sessions.py:576: in send
    r = adapter.send(request, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <requests.adapters.HTTPAdapter object at 0x7f72a2fd6990>
request = <PreparedRequest [GET]>, stream = False
timeout = <requests.packages.urllib3.util.timeout.Timeout object at 0x7f72a2fd6e90>
verify = False, cert = None, proxies = OrderedDict()

    def send(self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None):
        """Sends PreparedRequest object. Returns Response object.

            :param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
            :param stream: (optional) Whether to stream the request content.
            :param timeout: (optional) How long to wait for the server to send
                data before giving up, as a float, or a :ref:`(connect timeout,
                read timeout) <timeouts>` tuple.
            :type timeout: float or tuple
            :param verify: (optional) Whether to verify SSL certificates.
            :param cert: (optional) Any user-provided SSL certificate to be trusted.
            :param proxies: (optional) The proxies dictionary to apply to the request.
            """

        conn = self.get_connection(request.url, proxies)

        self.cert_verify(conn, request.url, verify, cert)
        url = self.request_url(request, proxies)
        self.add_headers(request)

        chunked = not (request.body is None or 'Content-Length' in request.headers)

        if isinstance(timeout, tuple):
            try:
                connect, read = timeout
                timeout = TimeoutSauce(connect=connect, read=read)
            except ValueError as e:
                # this may raise a string formatting error.
                err = ("Invalid timeout {0}. Pass a (connect, read) "
                       "timeout tuple, or a single float to set "
                       "both timeouts to the same value".format(timeout))
                raise ValueError(err)
        else:
            timeout = TimeoutSauce(connect=timeout, read=timeout)

        try:
            if not chunked:
                resp = conn.urlopen(
                    method=request.method,
                    url=url,
                    body=request.body,
                    headers=request.headers,
                    redirect=False,
                    assert_same_host=False,
                    preload_content=False,
                    decode_content=False,
                    retries=self.max_retries,
                    timeout=timeout
                )

            # Send the request.
            else:
                if hasattr(conn, 'proxy_pool'):
                    conn = conn.proxy_pool
                low_conn = conn._get_conn(timeout=DEFAULT_POOL_TIMEOUT)

                try:
                    low_conn.putrequest(request.method,
                                        url,
                                        skip_accept_encoding=True)

                    for header, value in request.headers.items():
                        low_conn.putheader(header, value)

                    low_conn.endheaders()

                    for i in request.body:
                        low_conn.send(hex(len(i))[2:].encode('utf-8'))
                        low_conn.send(b'\r\n')
                        low_conn.send(i)
                        low_conn.send(b'\r\n')
                    low_conn.send(b'0\r\n\r\n')

                    # Receive the response from the server
                    try:
                        # For Python 2.7+ versions, use buffering of HTTP
                        # responses
                        r = low_conn.getresponse(buffering=True)
                    except TypeError:
                        # For compatibility with Python 2.6 versions and back
                        r = low_conn.getresponse()

                    resp = HTTPResponse.from_httplib(
                        r,
                        pool=conn,
                        connection=low_conn,
                        preload_content=False,
                        decode_content=False
                    )
                except:
                    # If we hit any problems here, clean up the connection.
                    # Then, reraise so that we can handle the actual exception.
                    low_conn.close()
                    raise

        except (ProtocolError, socket.error) as err:
            raise ConnectionError(err, request=request)

        except MaxRetryError as e:
            if isinstance(e.reason, ConnectTimeoutError):
                # TODO: Remove this in 3.0.0: see #2811
                if not isinstance(e.reason, NewConnectionError):
                    raise ConnectTimeout(e, request=request)

            if isinstance(e.reason, ResponseError):
                raise RetryError(e, request=request)

>           raise ConnectionError(e, request=request)
E           ConnectionError: HTTPSConnectionPool(host='xx.xx.xx.xx,xx.xx.xx.xx', port=xxxxx): Max retries exceeded with url: /mgmt/tm/sys/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f72a28f2a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

cert       = None
chunked    = False
conn       = <requests.packages.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f72a9b192d0>
e          = MaxRetryError("HTTPSConnectionPool(host='xx.xx.xx.xx,xx.xx.xx.xx', port=xxxxx): ...ablish a new connection: [Errno -3] Temporary failure in name resolution',))",)
proxies    = OrderedDict()
request    = <PreparedRequest [GET]>
self       = <requests.adapters.HTTPAdapter object at 0x7f72a2fd6990>
stream     = False
timeout    = <requests.packages.urllib3.util.timeout.Timeout object at 0x7f72a2fd6e90>
url        = '/mgmt/tm/sys/'
verify     = False

/usr/local/lib/python2.7/dist-packages/requests/adapters.py:437: ConnectionError
```

##### Impacted Tests:
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `ESDTestJSON.test_create_esd`
  * Sum: `md5sum:11451ac525f3502bcfd1f7cba77ea78d`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyTestJSON.test_create_l7_redirect_to_pool_policy`
  * Sum: `md5sum:546618ef440a26d88d99f39135e2c5fc`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyTestJSON.test_create_l7_redirect_to_url_policy`
  * Sum: `md5sum:546618ef440a26d88d99f39135e2c5fc`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyTestJSON.test_create_l7_reject_policy`
  * Sum: `md5sum:546618ef440a26d88d99f39135e2c5fc`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_create_l7_reject_policy`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_policy_reject_header_contains`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_policy_reject_header_ends_with`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_policy_reject_many_rules`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_policy_reject_multi_policy_multi_rules`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONReject.test_policy_reject_three_rules`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `TestL7PolicyTestJSONRedirectToUrl.test_create_l7_redirect_to_url_policy`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `TestL7PolicyTestJSONRedirectToUrl.test_policy_redirect_url_contains`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONRedirectToPool.test_create_l7_redirect_to_pool_policy_file_type_contains`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyJSONRedirectToPool.test_create_l7_redirect_to_pool_policy_not_file_type`
  * Sum: `md5sum:0b7a46448bd7e35f9a27cd39b7a0d5eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_create_policy_no_rule`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_create_policy_one_rule`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_create_two_policies`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_delete_all_rules`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_delete_one_rule`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_delete_policy`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `L7PolicyRulesTestJSON.test_reorder_policies`
  * Sum: `md5sum:1d35b2ff32ffec5c1beae1c57f5e5464`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `MemberStatusTestJSON.test_disabled`
  * Sum: `md5sum:b5a132dcbf4d2dffda46c169430a6b10`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `MemberStatusTestJSON.test_no_monitor`
  * Sum: `md5sum:7a45caf89a1f8cb5b909fdb092a525eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `MemberStatusTestJSON.test_offline`
  * Sum: `md5sum:7a45caf89a1f8cb5b909fdb092a525eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `MemberStatusTestJSON.test_online`
  * Sum: `md5sum:7a45caf89a1f8cb5b909fdb092a525eb`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `PoolSyncTestJSON.test_pool_active_sync`
  * Sum: `md5sum:8cb50460dbc2d6078e939a832f0724d2`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `PoolSyncTestJSON.test_pool_member_active_sync`
  * Sum: `md5sum:8cb50460dbc2d6078e939a832f0724d2`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `PoolTestJSON.test_create_shared_detached_pools`
  * Sum: `md5sum:5553098a6be825125f5ba44125c3b800`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `PoolTestJSON.test_create_shared_pools`
  * Sum: `md5sum:5553098a6be825125f5ba44125c3b800`
* `openstack_driver_mitaka_ha-11.6.1-overcloud.2.consoleText`
  * Type: errors
  * Test: `ServiceBuilderTestJSON.test_service_builder`
  * Sum: `md5sum:beaef6ecead9b456c9bf64d644ad4711`

#### Agent Version
Mitaka - `87943414cebfd5461f33826d7a2c71ff192a947b`

#### Operating System
Nightly

#### OpenStack Release
Mitaka

#### Bug Severity 
Low

#### Deployment
HA

**Comment by ssorenso** [comment]
Another form of the failure:
```python
  0 ___________________ MemberSubnetTestJSON.test_member_selfips ___________________
  1 NOTE: Incompatible Exception Representation, displaying natively:
  2
  3 _StringException: pythonlogging:'': {{{2017-10-23 02:20:14,018 18404 INFO     [f5lbaasdriver.test.tempest.tests.api.test_member_subnets:MemberSubnetTestJSON] Finished: test_member_selfips}}}
  4
  5 Traceback (most recent call last):
  6   File "/home-local/jenkins/workspace/openstack/driver/mitaka/ha-11.6.1-overcloud/f5lbaasdriver/test/tempest/tests/api/test_member_subnets.py", line 78, in test_member_selfips
  7     config.f5_lbaasv2_driver.icontrol_password)
  8   File "/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py", line 124, in __init__
  9     self.post_configuration_setup()
 10   File "/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py", line 91, in post_configuration_setup
 11     self._get_tmos_version()
 12   File "/usr/local/lib/python2.7/dist-packages/f5/bigip/__init__.py", line 96, in _get_tmos_version
 13     response = connect.get(base_uri)
 14   File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 258, in wrapper
 15     response = method(self, REST_uri, **kwargs)
 16   File "/usr/local/lib/python2.7/dist-packages/icontrol/session.py", line 427, in get
 17     return self.session.get(uri, **kwargs)
 18   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
 19     return self.request('GET', url, **kwargs)
 20   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
 21     resp = self.send(prep, **send_kwargs)
 22   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
 23     r = adapter.send(request, **kwargs)
 24   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 437, in send
 25     raise ConnectionError(e, request=request)
 26 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.190.3.61,10.190.3.65', port=443): Max retries exceeded with url: /mgmt/tm/sys/ (Caused by NewConnectionError('<requests.packages.url    lib3.connection.VerifiedHTTPSConnection object at 0x7ff59272f8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by richbrowne** [comment]
If you look at the 'host' parameter in the call to HTTPSConnectionPool, I see 2 IP addresses.  Can we make sure that we are parsing the icontrol_driver host name correctly?

Rich
