### ISSUE TITLE
[DOC] broken link in cloudocs site

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-lbaasv2-driver#812]
#### Description

If you go to http://clouddocs.f5.com/products/openstack/lbaasv2-driver/newton/v10.0/ and you click in the following link, you will find that the link is broken
 
**Release**

Release 10.0.0 is compatible with OpenStack Newton. For more information, please see the F5® OpenStack [Releases, Versioning, and Support Matrix](http://f5-openstack-docs.readthedocs.org/en/latest/releases_and_versioning.html).
 
I hope this helps
 
Regards
 
                Ulises

**Comment by jlongstaf** [comment]
This is an old version of the docs before we migrated documentation to new system.
