### ISSUE TITLE
test_member_CLUDS uses incorrect test for member

### ISSUE THREAD

**Issue by jlongstaf** [F5Networks/f5-openstack-lbaasv2-driver#84]
test_member_CLUDS will fail because it incorrectly expects the return member to be formatted as ```<IP address>:<port>```, when the member may include a route designation after it's IP address. For example: 10.2.2.3%1:8080. Note that the return value route may likely be URL encoded (e.g., 10.2.2.3%251:8080). Here's the code and error output:
```
        address_plus_port =\
            '%s:%s' % (address, member_config['member']['protocol_port'])
>       assert address_plus_port in bigip_pool_member.selfLink
E       assert '10.2.3.100:80' in 'https://localhost/mgmt/tm/ltm/pool/~Project_f49fb47c39b54a2d9e45719e73080792~test_pool_anur23rgg/members/~Project_f49fb47c39b54a2d9e45719e73080792~10.2.3.100%251:80?ver=11.6.0'
```

**Comment by zancas** [comment]
Acknowledged.

**Comment by zancas** [comment]
@jlongstaf shall open the PR with the issue-resolving code against master, or liberty?

**Comment by dflanigan** [comment]
Now part of Tempest.
