### ISSUE TITLE
[DOC]: broken link f5-environment-generator

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-lbaasv2-driver#848]
#### Description
Hi

This seems to apply to all documentation released, ie:

http://clouddocs.f5.com/products/openstack/lbaasv2-driver/newton/v10.0/includes/topic_environment-generator.html#f5-environment-generator

http://clouddocs.f5.com/products/openstack/lbaasv2-driver/liberty/v8.2/includes/topic_environment-generator.html#f5-environment-generator

**Comment by jputrino** [comment]
Hi @alonsocamaro,

Yes, we are aware of this issue. The tagged versions are snapshots of the project at the commit at which they were created, which was *before* the transition from read the docs to clouddocs.f5.com.

I recommend looking at the version pertaining to the OpenStack release (not the tagged release version). As of the latest release (10.1, 9.4, 8.3.6) the tagged versions have updated links.  

For example:
http://clouddocs.f5.com/products/openstack/lbaasv2-driver/newton/environment-generator.html 
http://clouddocs.f5.com/products/openstack/lbaasv2-driver/newton/v10.1/environment-generator.html
