### ISSUE TITLE
testenv migration: Transport URL credentials are incorrect for testenv openstack deployment

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-lbaasv2-driver#860]
#### Description
This test issue is only applicable for the testenv migration. The transport url defined [here](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/mitaka/systest/scripts/configure_test_infra.sh#L48) in test setup does not specify the correct credentials for a testenv-deployed openstack. The actual credentials can be found by inspecting the /etc/neutron/neutron.conf file and searching for 'transport_url'. This will allow the API tests to correctly setup an rpc client.

**Comment by richbrowne** [comment]
This is fixed by the test migration.
