### ISSUE TITLE
F5 agent running inhibits creation of HA Proxy loadbalancers

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-lbaasv2-driver#88]
*When the haproxy lbaas service is invoked the first thing that will happen is to find an agent to perform the action.  It queries the database for all active agents of type AGENT_TYPE_LOADBALANCER.  The result will be all active loadbalancers, including the f5 loadbalancer.  In the code printed above, it then queries every active agent to see if the device driver reported in the config matches the one passed in to the method.  The F5 LBaaS driver does not define this key in the agent config and so the exception results when the F5 LBaaS agent is processed.

**Comment by zancas** [comment]
Is the fix to ensure that the agent has a list of supported drivers in its config dict?

**Comment by richbrowne** [comment]
This was fixed in v2 and v1
